
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnpdieomxraerzgocofk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucGRpZW9teHJhZXJ6Z29jb2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDI0NzEsImV4cCI6MjA1ODk3ODQ3MX0.BcLb9NnIeaV6FOymxkP4pGU91uo35MiXe2cGj2P6Ea4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a mock Supabase client for development
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
